"""Deterministic generation of illustrative synthetic experiments.

**These are not simulations.** Each scenario draws a closed-form curve chosen
for being smooth, cheap and reproducible. No sedimentation or diffusion
coefficient, molar mass or any other physical parameter is used to produce them,
and none may be inferred from them. A generated experiment is structurally
valid data for testing and demonstration; it is never scientifically valid data.

Randomness comes from a :class:`numpy.random.Generator` seeded from the config.
NumPy's global random state is never read or written.
"""

from __future__ import annotations

from datetime import UTC, datetime

import numpy as np
from numpy.typing import NDArray

from openauc.models import (
    AUCExperiment,
    ExperimentMetadata,
    ImportProvenance,
    InstrumentMetadata,
    Observations,
    OpticalSystem,
    Quantity,
    RadiusAxisMode,
    SampleMetadata,
    ScanMetadata,
    Unit,
)
from openauc.synthetic.config import (
    MetadataCompleteness,
    Scenario,
    SyntheticExperimentConfig,
)

__all__ = ["generate_experiment"]

#: Attached to every generated experiment so its origin is unmistakable.
SYNTHETIC_NOTE = (
    "Illustrative synthetic data generated by openauc.synthetic. Not a physically "
    "validated simulation of an analytical ultracentrifugation experiment, and "
    "not a Lamm-equation solution. No physical parameters were used or may be "
    "inferred."
)

#: Optical systems cycled through by the mixed-optics scenario.
_MIXED_SYSTEMS = (
    OpticalSystem.ABSORBANCE,
    OpticalSystem.INTERFERENCE,
    OpticalSystem.FLUORESCENCE,
)


def _radius_axis(config: SyntheticExperimentConfig) -> NDArray[np.float64]:
    return np.linspace(
        config.radius_min, config.radius_max, config.n_points, dtype=np.float64
    )


def _noise(
    rng: np.random.Generator, shape: tuple[int, ...], level: float
) -> NDArray[np.float64]:
    if level <= 0.0:
        return np.zeros(shape, dtype=np.float64)
    return np.asarray(rng.normal(0.0, level, size=shape), dtype=np.float64)


def _moving_boundary(
    radius: NDArray[np.float64], config: SyntheticExperimentConfig, index: int
) -> NDArray[np.float64]:
    """An illustrative step whose midpoint advances outward with scan index.

    A logistic curve in radius. Chosen because it is smooth, monotonic and
    trivially reproducible — **not** because it models sedimentation.
    """
    span = config.radius_max - config.radius_min
    fraction = (
        0.15 if config.n_scans == 1 else 0.15 + 0.6 * index / (config.n_scans - 1)
    )
    midpoint = config.radius_min + fraction * span
    width = max(span / 40.0, 1e-9)
    return np.asarray(
        config.signal_scale / (1.0 + np.exp(-(radius - midpoint) / width)),
        dtype=np.float64,
    )


def _equilibrium_profile(
    radius: NDArray[np.float64], config: SyntheticExperimentConfig
) -> NDArray[np.float64]:
    """A stationary curved profile, identical in every scan.

    An exponential in ``r^2`` normalised to the signal scale. The shape is a
    convenient smooth curve; **no equilibrium condition is modelled** and no
    molar mass or buoyancy term is involved.
    """
    reduced = radius**2 - config.radius_min**2
    span = max(config.radius_max**2 - config.radius_min**2, 1e-12)
    curve = np.exp(2.0 * reduced / span)
    return np.asarray(config.signal_scale * curve / curve.max(), dtype=np.float64)


def _static_profile(
    radius: NDArray[np.float64], config: SyntheticExperimentConfig
) -> NDArray[np.float64]:
    """A fixed smooth ramp, repeated in every scan."""
    span = max(config.radius_max - config.radius_min, 1e-12)
    normalised = (radius - config.radius_min) / span
    return np.asarray(config.signal_scale * (0.2 + 0.6 * normalised), dtype=np.float64)


def _scan_signal(
    radius: NDArray[np.float64],
    config: SyntheticExperimentConfig,
    index: int,
) -> NDArray[np.float64]:
    """The noiseless curve for one scan, chosen by scenario."""
    if config.scenario is Scenario.EQUILIBRIUM_PROFILE:
        return _equilibrium_profile(radius, config)
    if config.scenario in (Scenario.STATIC_PROFILE, Scenario.EMPTY_SCANS):
        return _static_profile(radius, config)
    return _moving_boundary(radius, config, index)


def _per_scan_radius(
    config: SyntheticExperimentConfig, index: int
) -> NDArray[np.float64]:
    """A distinct radius vector for one scan.

    Length and start shift deterministically with the scan index, so scans
    genuinely differ. Values are generated already ascending and are **never
    sorted or resampled afterwards** — the stored order is the generated order.
    """
    span = config.radius_max - config.radius_min
    offset = (index % 5) * span / 200.0
    length = max(config.n_points - (index % 4), 1)
    return np.linspace(
        config.radius_min + offset, config.radius_max, length, dtype=np.float64
    )


def _observations(
    config: SyntheticExperimentConfig,
    rng: np.random.Generator,
    scan_ids: list[str],
) -> Observations:
    unit = config.effective_signal_unit
    if config.effective_radius_axis_mode is RadiusAxisMode.SHARED:
        radius = _radius_axis(config)
        rows = [_scan_signal(radius, config, i) for i in range(config.n_scans)]
        signal = np.vstack(rows) if rows else np.zeros((0, config.n_points))
        signal = signal + _noise(rng, signal.shape, config.noise_level)
        return Observations.from_shared_axis(
            radius=radius,
            signal=signal,
            scan_ids=scan_ids,
            signal_unit=unit,
            radius_unit=Unit.CENTIMETRE,
        )

    radii: list[NDArray[np.float64]] = []
    signals: list[NDArray[np.float64]] = []
    empty_every = 3
    for index in range(config.n_scans):
        # The empty-scans scenario leaves selected scans with no observations at
        # all; the canonical model represents that with an all-false mask row.
        if config.scenario is Scenario.EMPTY_SCANS and index % empty_every == 1:
            radii.append(np.empty(0, dtype=np.float64))
            signals.append(np.empty(0, dtype=np.float64))
            continue
        radius = _per_scan_radius(config, index)
        signal = _scan_signal(radius, config, index)
        signal = signal + _noise(rng, signal.shape, config.noise_level)
        radii.append(radius)
        signals.append(signal)
    return Observations.from_per_scan(
        radii=radii,
        signals=signals,
        scan_ids=scan_ids,
        signal_unit=unit,
        radius_unit=Unit.CENTIMETRE,
    )


def _elapsed(config: SyntheticExperimentConfig, index: int) -> Quantity:
    """Elapsed time for a scan, or an explicit absence for sparse metadata."""
    if config.scenario is Scenario.SPARSE_METADATA:
        # Keep the three kinds of absence distinguishable and deterministic.
        if index % 3 == 1:
            return Quantity.missing()
        if index % 3 == 2:
            return Quantity.unknown()
    return Quantity.of(float(index) * config.elapsed_seconds_step, Unit.SECOND)


def _optical_system(config: SyntheticExperimentConfig, index: int) -> OpticalSystem:
    if config.scenario is Scenario.MIXED_OPTICS:
        return _MIXED_SYSTEMS[index % len(_MIXED_SYSTEMS)]
    if config.scenario is Scenario.SPARSE_METADATA and index % 4 == 3:
        return OpticalSystem.UNKNOWN
    return config.optical_system


def _scan_metadata(
    config: SyntheticExperimentConfig, index: int, scan_id: str
) -> ScanMetadata:
    completeness = config.metadata_completeness
    sparse = config.scenario is Scenario.SPARSE_METADATA
    minimal = completeness is MetadataCompleteness.MINIMAL

    wavelength: Quantity | None = None
    rotor_speed: Quantity | None = None
    temperature: Quantity | None = None
    cell: str | None = None
    channel: str | None = None

    if not minimal:
        cell = "1"
        channel = "A"
        wavelength = Quantity.of(280.0, Unit.NANOMETRE)
        rotor_speed = Quantity.of(45000.0, Unit.RPM)
        temperature = Quantity.of(20.0, Unit.DEGREE_CELSIUS)

    if sparse:
        # Explicit, distinguishable absences rather than omitted fields.
        wavelength = Quantity.unknown() if index % 2 == 0 else None
        rotor_speed = Quantity.missing()
        temperature = Quantity.not_applicable()
        cell = "1" if index % 2 == 0 else None
        channel = None

    return ScanMetadata(
        scan_id=scan_id,
        index=index,
        elapsed_time=_elapsed(config, index),
        cell=cell,
        channel=channel,
        wavelength=wavelength,
        optical_system=_optical_system(config, index),
        rotor_speed=rotor_speed,
        temperature=temperature,
        annotations=("synthetic",),
    )


def _samples(config: SyntheticExperimentConfig) -> tuple[SampleMetadata, ...]:
    completeness = config.metadata_completeness
    if completeness is MetadataCompleteness.MINIMAL:
        return ()
    if config.scenario is Scenario.SPARSE_METADATA:
        return (
            SampleMetadata(
                sample_id="synthetic-sample",
                description="Synthetic sample with deliberately sparse metadata.",
                density=Quantity.unknown(),
                viscosity=Quantity.missing(),
                partial_specific_volume=Quantity.not_applicable(),
            ),
        )
    if completeness is MetadataCompleteness.TYPICAL:
        return (
            SampleMetadata(
                sample_id="synthetic-sample",
                description="Synthetic sample. Not a real measurement.",
                buffer_description="synthetic buffer",
            ),
        )
    return (
        SampleMetadata(
            sample_id="synthetic-sample",
            description="Synthetic sample. Not a real measurement.",
            buffer_description="synthetic buffer",
            concentration=Quantity.of(0.5, Unit.OTHER, unit_label="mg/mL"),
            density=Quantity.of(1.0, Unit.OTHER, unit_label="g/mL"),
            viscosity=Quantity.of(0.01, Unit.OTHER, unit_label="P"),
            partial_specific_volume=Quantity.of(0.73, Unit.OTHER, unit_label="mL/g"),
            notes="Values are illustrative constants, not measurements.",
        ),
    )


def _instrument(config: SyntheticExperimentConfig) -> InstrumentMetadata | None:
    if config.metadata_completeness is MetadataCompleteness.MINIMAL:
        return None
    optical = (
        OpticalSystem.UNKNOWN
        if config.scenario is Scenario.MIXED_OPTICS
        else config.optical_system
    )
    return InstrumentMetadata(
        manufacturer="synthetic",
        model="synthetic-analytical-ultracentrifuge",
        rotor_id="synthetic-rotor",
        nominal_speed=Quantity.of(45000.0, Unit.RPM),
        temperature=Quantity.of(20.0, Unit.DEGREE_CELSIUS),
        centrepiece="synthetic-2-channel",
        optical_system=optical,
    )


def _experiment_metadata(config: SyntheticExperimentConfig) -> ExperimentMetadata:
    complete = config.metadata_completeness is MetadataCompleteness.COMPLETE
    return ExperimentMetadata(
        experiment_id=config.experiment_id,
        name=config.name,
        description=SYNTHETIC_NOTE if complete else None,
        experiment_type=config.experiment_type,
        acquired_at=datetime(2026, 1, 1, tzinfo=UTC) if complete else None,
        operator="synthetic-generator" if complete else None,
        notes=SYNTHETIC_NOTE,
    )


def _provenance(config: SyntheticExperimentConfig) -> ImportProvenance:
    """Provenance recording that this data was generated, not imported.

    No source path or checksum is invented: nothing was read from disk. The
    generator records what it actually did.
    """
    from openauc import __version__

    return ImportProvenance(
        parser_name="openauc.synthetic",
        parser_version=__version__,
        transformations=(f"generated scenario={config.scenario.value}",),
        assumptions=(
            SYNTHETIC_NOTE,
            f"seed={config.seed}",
            f"noise_level={config.noise_level:g}",
        ),
    )


def _scan_ids(config: SyntheticExperimentConfig) -> list[str]:
    width = max(len(str(config.n_scans)), 3)
    return [f"scan_{index + 1:0{width}d}" for index in range(config.n_scans)]


def generate_experiment(config: SyntheticExperimentConfig) -> AUCExperiment:
    """Generate an illustrative synthetic experiment.

    The same configuration always yields the same experiment. Generated values
    and their order are preserved exactly: nothing is sorted, resampled or
    interpolated after construction.

    The result is **illustrative synthetic data**, never a physically validated
    simulation. It carries no sedimentation or diffusion coefficient, no molar
    mass and no fitted parameter, and none may be inferred from it.

    Args:
        config: The dataset description, including the seed.

    Returns:
        A canonical :class:`~openauc.models.AUCExperiment`.
    """
    rng = np.random.default_rng(config.seed)
    observation_ids = _scan_ids(config)
    observations = _observations(config, rng, observation_ids)

    metadata_ids = list(observation_ids)
    if config.scenario is Scenario.INVALID_STRUCTURE:
        # A deliberate cross-object inconsistency, built only from objects the
        # model permits: the second metadata record duplicates the first
        # identifier, so the metadata no longer matches the observations. This
        # yields duplicate_scan_id and scan_id_mismatch, both ARCHIVAL errors.
        # No construction invariant is bypassed.
        metadata_ids[1] = metadata_ids[0]

    scans = tuple(
        _scan_metadata(config, index, scan_id)
        for index, scan_id in enumerate(metadata_ids)
    )

    return AUCExperiment(
        metadata=_experiment_metadata(config),
        scans=scans,
        observations=observations,
        samples=_samples(config),
        instrument=_instrument(config),
        provenance=_provenance(config),
    )
