"""Write generated experiments out in the formats openauc can read back.

Manifests are built with the real :class:`~openauc.formats.manifest.GenericManifest`
models and archives with the real AUCX writer, so these functions cannot drift
away from what the readers expect. Only the delimited *table* is written here,
because the parsers read tables but never write them.

An optional column is emitted **only when every scan carries that value as
PRESENT**. A generic delimited file has no way to say "unknown" as distinct from
"missing", so rather than inventing a convention the column is omitted, which
reloads as absent. AUCX preserves the distinction exactly; delimited output does
not. That limitation is documented, not worked around.
"""

from __future__ import annotations

import json
from collections.abc import Callable, Sequence
from pathlib import Path

from openauc.exceptions import OpenAUCError
from openauc.formats.aucx import export_aucx
from openauc.formats.manifest import (
    GenericManifest,
    ManifestDefaults,
    ManifestExperiment,
    ManifestInstrument,
    ManifestSample,
    WideColumns,
    WideScanColumn,
)
from openauc.models import (
    AUCExperiment,
    Quantity,
    RadiusAxisMode,
    ScanMetadata,
    Unit,
    ValueStatus,
)

__all__ = [
    "SyntheticWriteError",
    "write_aucx",
    "write_generic_long",
    "write_generic_wide",
]

DATA_FILENAME = "scans.csv"
MANIFEST_FILENAME = "manifest.json"

_SYNTHETIC_NOTE = (
    "Illustrative synthetic data generated by openauc.synthetic. Not a "
    "physically validated simulation and not a real measurement."
)


class SyntheticWriteError(OpenAUCError):
    """Raised when a generated experiment cannot be written as requested."""


def _present(quantity: Quantity | None) -> bool:
    return quantity is not None and quantity.status is ValueStatus.PRESENT


def _all_present(
    scans: Sequence[ScanMetadata], accessor: Callable[[ScanMetadata], Quantity | None]
) -> bool:
    return bool(scans) and all(_present(accessor(scan)) for scan in scans)


def _value(quantity: Quantity | None) -> float:
    assert quantity is not None and quantity.value is not None
    return quantity.value


def _prepare_directory(directory: Path, *, overwrite: bool) -> None:
    directory.mkdir(parents=True, exist_ok=True)
    for name in (MANIFEST_FILENAME, DATA_FILENAME):
        target = directory / name
        if target.exists() and not overwrite:
            raise SyntheticWriteError(
                f"refusing to overwrite existing file: {target}; "
                "pass overwrite=True to replace it"
            )


def _manifest_common(experiment: AUCExperiment, *, layout: str) -> dict[str, object]:
    metadata = experiment.metadata
    instrument = experiment.instrument
    return {
        "schema_version": "1.0",
        "format": layout,
        "data_file": DATA_FILENAME,
        "experiment": ManifestExperiment(
            experiment_id=metadata.experiment_id,
            name=metadata.name,
            description=metadata.description,
            experiment_type=metadata.experiment_type,
            operator=metadata.operator,
            notes=_SYNTHETIC_NOTE,
        ),
        "instrument": (
            ManifestInstrument(
                manufacturer=instrument.manufacturer,
                model=instrument.model,
                serial_number=instrument.serial_number,
                rotor_id=instrument.rotor_id,
                nominal_speed_rpm=(
                    _value(instrument.nominal_speed)
                    if _present(instrument.nominal_speed)
                    else None
                ),
                temperature_c=(
                    _value(instrument.temperature)
                    if _present(instrument.temperature)
                    else None
                ),
                centrepiece=instrument.centrepiece,
            )
            if instrument is not None
            else None
        ),
        "samples": tuple(
            ManifestSample(
                sample_id=sample.sample_id,
                description=sample.description,
                buffer_description=sample.buffer_description,
            )
            for sample in experiment.samples
        ),
        "notes": _SYNTHETIC_NOTE,
    }


def _write_manifest(manifest: GenericManifest, directory: Path) -> Path:
    payload = manifest.model_dump(mode="json", exclude_none=True)
    target = directory / MANIFEST_FILENAME
    target.write_text(
        json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    return target


def write_generic_long(
    experiment: AUCExperiment, directory: str | Path, *, overwrite: bool = False
) -> Path:
    """Write ``experiment`` as a generic-long CSV plus its manifest.

    Returns the directory written. Reload it with ``openauc.load(directory)``.

    Optional per-scan columns are emitted only when every scan carries the value
    as PRESENT — see the module docstring for why.
    """
    target = Path(directory)
    _prepare_directory(target, overwrite=overwrite)
    scans = experiment.scans
    observations = experiment.observations

    include_elapsed = _all_present(scans, lambda s: s.elapsed_time)
    include_wavelength = _all_present(scans, lambda s: s.wavelength)
    include_speed = _all_present(scans, lambda s: s.rotor_speed)
    include_temperature = _all_present(scans, lambda s: s.temperature)
    include_cell = bool(scans) and all(s.cell is not None for s in scans)
    include_channel = bool(scans) and all(s.channel is not None for s in scans)
    include_optical = len({s.optical_system for s in scans}) > 1

    header = ["scan", "radius_cm", "signal"]
    if include_elapsed:
        header.append("elapsed_seconds")
    if include_cell:
        header.append("cell")
    if include_channel:
        header.append("channel")
    if include_wavelength:
        header.append("wavelength_nm")
    if include_optical:
        header.append("optical_system")
    if include_speed:
        header.append("rotor_speed_rpm")
    if include_temperature:
        header.append("temperature_c")

    by_id = {scan.scan_id: scan for scan in scans}
    lines = [",".join(header)]
    for scan_id in observations.scan_ids:
        radius, signal = observations.scan_vectors(scan_id)
        scan = by_id.get(scan_id)
        for r, s in zip(radius, signal, strict=True):
            row = [scan_id, f"{r:.10g}", f"{s:.10g}"]
            if scan is not None:
                if include_elapsed:
                    row.append(f"{_value(scan.elapsed_time):.10g}")
                if include_cell:
                    row.append(str(scan.cell))
                if include_channel:
                    row.append(str(scan.channel))
                if include_wavelength:
                    row.append(f"{_value(scan.wavelength):.10g}")
                if include_optical:
                    row.append(scan.optical_system.value)
                if include_speed:
                    row.append(f"{_value(scan.rotor_speed):.10g}")
                if include_temperature:
                    row.append(f"{_value(scan.temperature):.10g}")
            lines.append(",".join(row))

    (target / DATA_FILENAME).write_text("\n".join(lines) + "\n", encoding="utf-8")

    common = _manifest_common(experiment, layout="generic-long")
    defaults = ManifestDefaults(
        optical_system=(
            None if include_optical else next(iter({s.optical_system for s in scans}))
        )
        if scans
        else None,
        signal_unit=(
            observations.signal_unit.value
            if observations.signal_unit is not Unit.UNKNOWN
            else None
        ),
    )
    _write_manifest(GenericManifest(**common, defaults=defaults), target)  # type: ignore[arg-type]
    return target


def write_generic_wide(
    experiment: AUCExperiment, directory: str | Path, *, overwrite: bool = False
) -> Path:
    """Write ``experiment`` as a generic-wide CSV plus its manifest.

    Raises:
        SyntheticWriteError: if the experiment does not share one radius axis.
            Wide layout has a single radius column, so per-scan axes cannot be
            expressed without resampling — which openauc never does.
    """
    target = Path(directory)
    observations = experiment.observations
    if observations.mode is not RadiusAxisMode.SHARED:
        raise SyntheticWriteError(
            "wide layout needs one shared radius axis, but this experiment uses "
            f"{observations.mode.value!r} axes. Writing it wide would require "
            "resampling onto a common grid, which openauc never does; use "
            "write_generic_long or write_aucx instead."
        )
    _prepare_directory(target, overwrite=overwrite)

    scan_ids = observations.scan_ids
    radius, _ = (
        observations.scan_vectors(scan_ids[0])
        if scan_ids
        else (observations.valid_radius_values(), None)
    )
    columns = [f"{scan_id}" for scan_id in scan_ids]
    lines = [",".join(["radius_cm", *columns])]
    signals = [observations.scan_vectors(scan_id)[1] for scan_id in scan_ids]
    for row_index, r in enumerate(radius):
        values = [f"{signal[row_index]:.10g}" for signal in signals]
        lines.append(",".join([f"{r:.10g}", *values]))
    (target / DATA_FILENAME).write_text("\n".join(lines) + "\n", encoding="utf-8")

    by_id = {scan.scan_id: scan for scan in experiment.scans}
    wide_scans = []
    for scan_id in scan_ids:
        scan = by_id.get(scan_id)
        wide_scans.append(
            WideScanColumn(
                column=scan_id,
                scan_id=scan_id,
                elapsed_seconds=(
                    _value(scan.elapsed_time)
                    if scan is not None and _present(scan.elapsed_time)
                    else None
                ),
                wavelength_nm=(
                    _value(scan.wavelength)
                    if scan is not None and _present(scan.wavelength)
                    else None
                ),
                optical_system=scan.optical_system if scan is not None else None,
                rotor_speed_rpm=(
                    _value(scan.rotor_speed)
                    if scan is not None and _present(scan.rotor_speed)
                    else None
                ),
                temperature_c=(
                    _value(scan.temperature)
                    if scan is not None and _present(scan.temperature)
                    else None
                ),
                cell=scan.cell if scan is not None else None,
                channel=scan.channel if scan is not None else None,
            )
        )

    common = _manifest_common(experiment, layout="generic-wide")
    manifest = GenericManifest(
        **common,  # type: ignore[arg-type]
        defaults=ManifestDefaults(
            signal_unit=(
                observations.signal_unit.value
                if observations.signal_unit is not Unit.UNKNOWN
                else None
            )
        ),
        columns=WideColumns(radius="radius_cm", scans=tuple(wide_scans)),
    )
    _write_manifest(manifest, target)
    return target


def write_aucx(
    experiment: AUCExperiment, path: str | Path, *, overwrite: bool = False
) -> Path:
    """Write ``experiment`` to an AUCX archive.

    A thin pass-through to :func:`openauc.export_aucx`, which round-trips the
    canonical model exactly — including the missing/unknown/not-applicable
    distinctions that delimited output cannot carry.

    Raises:
        ArchiveError: if the destination exists and ``overwrite`` is False.
    """
    return export_aucx(experiment, path, overwrite=overwrite)
