"""Public API surface for openauc.

Import from here (or the top-level ``openauc`` package) for the stable public
contract. Internal module paths are not part of that contract and may change
between releases without notice.

Phase 2 adds the canonical data model. The model types are also available from
``openauc.models``; they are re-exported here as the curated top-level surface.
"""

from __future__ import annotations

from openauc import __version__
from openauc.exceptions import (
    AmbiguousFormatError,
    ArchiveError,
    DataConflictError,
    FormatError,
    ManifestError,
    ObservationError,
    OpenAUCError,
    ParseError,
    StructuralValidationError,
    UnsupportedFormatError,
    ValidationError,
)
from openauc.formats import (
    DetectionResult,
    FormatInfo,
    GenericManifest,
    available_formats,
    load,
)
from openauc.models import (
    AnalysisKind,
    AnalysisReadiness,
    AUCExperiment,
    ExperimentMetadata,
    ExperimentSummary,
    ExperimentType,
    ImportProvenance,
    InstrumentMetadata,
    MetadataPresence,
    Observations,
    OpticalSystem,
    Quantity,
    RadiusAxisMode,
    ReadinessAssessment,
    ReadinessStatus,
    SampleMetadata,
    ScanMetadata,
    Unit,
    ValidationCounts,
    ValidationIssue,
    ValidationReport,
    ValidationSeverity,
    ValidationTier,
    ValueProvenance,
    ValueRange,
    ValueStatus,
    assess_experiment_readiness,
    summarise_experiment,
    validate_experiment,
    validate_experiment_structure,
)

__all__ = [
    "AUCExperiment",
    "AmbiguousFormatError",
    "AnalysisKind",
    "AnalysisReadiness",
    "ArchiveError",
    "DataConflictError",
    "DetectionResult",
    "ExperimentMetadata",
    "ExperimentSummary",
    "ExperimentType",
    "FormatError",
    "FormatInfo",
    "GenericManifest",
    "ImportProvenance",
    "InstrumentMetadata",
    "ManifestError",
    "MetadataPresence",
    "ObservationError",
    "Observations",
    "OpenAUCError",
    "OpticalSystem",
    "ParseError",
    "Quantity",
    "RadiusAxisMode",
    "ReadinessAssessment",
    "ReadinessStatus",
    "SampleMetadata",
    "ScanMetadata",
    "StructuralValidationError",
    "Unit",
    "UnsupportedFormatError",
    "ValidationCounts",
    "ValidationError",
    "ValidationIssue",
    "ValidationReport",
    "ValidationSeverity",
    "ValidationTier",
    "ValueProvenance",
    "ValueRange",
    "ValueStatus",
    "__version__",
    "assess_experiment_readiness",
    "available_formats",
    "load",
    "summarise_experiment",
    "validate_experiment",
    "validate_experiment_structure",
]
